[2025-05-08T13:21:35.200-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T13:21:35.207-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: request_operation.RequestTrading scheduled__2025-05-08T18:20:40+00:00 [queued]>
[2025-05-08T13:21:35.211-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: request_operation.RequestTrading scheduled__2025-05-08T18:20:40+00:00 [queued]>
[2025-05-08T13:21:35.211-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-08T13:21:35.225-0500] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): RequestTrading> on 2025-05-08 18:20:40+00:00
[2025-05-08T13:21:35.230-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'request_operation', 'RequestTrading', 'scheduled__2025-05-08T18:20:40+00:00', '--job-id', '1708', '--raw', '--subdir', 'DAGS_FOLDER/operations.py', '--cfg-path', '/tmp/tmpus1cy7bb']
[2025-05-08T13:21:35.231-0500] {standard_task_runner.py:105} INFO - Job 1708: Subtask RequestTrading
[2025-05-08T13:21:35.232-0500] {logging_mixin.py:190} WARNING - /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=72007) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-08T13:21:35.232-0500] {standard_task_runner.py:72} INFO - Started process 72032 to run task
[2025-05-08T13:21:35.256-0500] {task_command.py:467} INFO - Running <TaskInstance: request_operation.RequestTrading scheduled__2025-05-08T18:20:40+00:00 [running]> on host DESKTOP-0R7MK50.
[2025-05-08T13:21:35.308-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='request_operation' AIRFLOW_CTX_TASK_ID='RequestTrading' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T18:20:40+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-08T18:20:40+00:00'
[2025-05-08T13:21:35.308-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-08T13:21:36.500-0500] {logging_mixin.py:190} WARNING - /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/urllib3/connectionpool.py:1097 InsecureRequestWarning: Unverified HTTPS request is being made to host 'auth.iqoption.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-05-08T13:21:37.272-0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/iqoptions_bot/dags/operations.py", line 50, in RequestTrading
    chequeo_op = API.OperationIQ(activo=goal, direccion=direccion, monto=monto, expiracion=expiracion)
                 ^^^^^^^^^^^^^^^
AttributeError: 'ConectionApi' object has no attribute 'OperationIQ'
[2025-05-08T13:21:37.276-0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=request_operation, task_id=RequestTrading, run_id=scheduled__2025-05-08T18:20:40+00:00, execution_date=20250508T182040, start_date=20250508T182135, end_date=20250508T182137
[2025-05-08T13:21:37.300-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-08T13:21:37.301-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 1708 for task RequestTrading ('ConectionApi' object has no attribute 'OperationIQ'; 72032)
Traceback (most recent call last):
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/iqoptions_bot/dags/operations.py", line 50, in RequestTrading
    chequeo_op = API.OperationIQ(activo=goal, direccion=direccion, monto=monto, expiracion=expiracion)
                 ^^^^^^^^^^^^^^^
AttributeError: 'ConectionApi' object has no attribute 'OperationIQ'
[2025-05-08T13:21:37.310-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-08T13:21:37.316-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T13:21:37.316-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
