[2025-04-28T21:03:21.538-0500] {processor.py:186} INFO - Started process (PID=17212) to work on /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:03:21.538-0500] {processor.py:914} INFO - Processing file /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-28T21:03:21.540-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:03:21.539-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:03:21.542-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:03:21.541-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-28T21:03:21.542-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:03:21.542-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-28T21:03:21.542-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:03:21.548-0500] {processor.py:208} INFO - Processing /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-04-28T21:04:18.909-0500] {processor.py:186} INFO - Started process (PID=17656) to work on /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:04:18.911-0500] {processor.py:914} INFO - Processing file /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-28T21:04:18.912-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:04:18.912-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:04:18.914-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:04:18.914-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-28T21:04:18.914-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:04:18.914-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-28T21:04:18.915-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:04:18.925-0500] {processor.py:208} INFO - Processing /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-04-28T21:05:12.839-0500] {processor.py:186} INFO - Started process (PID=17849) to work on /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:05:12.844-0500] {processor.py:914} INFO - Processing file /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-28T21:05:12.845-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:05:12.845-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:05:12.848-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:05:12.847-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-28T21:05:12.848-0500] {logging_mixin.py:190} INFO - [2025-04-28T21:05:12.848-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-28T21:05:12.848-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-28T21:05:12.856-0500] {processor.py:208} INFO - Processing /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
